[build]
  # Directorio donde se encuentran las funciones
  functions = "netlify/functions"

[functions]
  # Configuraci贸n para todas las funciones
  node_bundler = "esbuild"

[[redirects]]
  # Redirecci贸n para el endpoint de la API
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  # Headers de seguridad para todas las rutas
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  # CORS headers para la API
  for = "/api/*"
  [headers.values]
    # Origin permitido definido por variable de entorno
    Access-Control-Allow-Origin = "${ALLOWED_ORIGIN}"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Variables de entorno requeridas
[build.environment]
  NODE_VERSION = "18"
  # Valor por defecto para desarrollo local
  ALLOWED_ORIGIN = "http://localhost:3000"

[context.production.environment]
  # Origin permitido en producci贸n
  ALLOWED_ORIGIN = "https://example.com"

# Configuraci贸n de desarrollo local
[dev]
  port = 8888
  targetPort = 3000
  autoLaunch = true
