[build]
  # Directorio donde se encuentran las funciones
  functions = "netlify/functions"

[functions]
  # Configuración para todas las funciones
  node_bundler = "esbuild"

[[redirects]]
  # Redirección para el endpoint de la API
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  # Headers de seguridad para todas las rutas
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  # CORS headers para la API
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Variables de entorno requeridas
[build.environment]
  NODE_VERSION = "18"

# Configuración de desarrollo local
[dev]
  port = 8888
  targetPort = 3000
  autoLaunch = true
